// Deprecated reference file.
// This template is no longer loaded by the app; the active notebook source is
// `gl8-growth.notebook.json`. Keep this file only as a maintenance reference.

import type { ModelDefinition, SimulationOptions } from "@sfcr/core";

import { editorStateFromModel } from "../../lib/editorModel";
import type { NotebookDocument } from "../types";

const growthEquationTuples = [
  ["Yk", "Ske + INke - INk[-1]"],
  ["Ske", "beta * Sk + (1 - beta) * Sk[-1] * (1 + (GRpr + RA))"],
  ["INke", "INk[-1] + gamma * (INkt - INk[-1])"],
  ["INkt", "sigmat * Ske"],
  ["INk", "INk[-1] + Yk - Sk - NPL / UC"],
  ["Kk", "Kk[-1] * (1 + GRk)"],
  ["GRk", "gamma0 + gammau * U[-1] - gammar * RRl"],
  ["U", "Yk / Kk[-1]"],
  ["RRl", "((1 + Rl) / (1 + PI)) - 1"],
  ["PI", "(P - P[-1]) / P[-1]"],
  ["Ik", "(Kk - Kk[-1]) + delta * Kk[-1]"],
  ["Sk", "Ck + Gk + Ik"],
  ["S", "Sk * P"],
  ["IN", "INk * UC"],
  ["INV", "Ik * P"],
  ["K", "Kk * P"],
  ["Y", "Sk * P + (INk - INk[-1]) * UC"],
  ["omegat", "exp(omega0 + omega1 * log(PR) + omega2 * log(ER + z3 * (1 - ER) - z4 * BANDt + z5 * BANDb))"],
  ["ER", "N[-1] / Nfe[-1]"],
  ["z3a", "if (ER > (1 - BANDb)) {1} else {0}"],
  ["z3b", "if (ER <= (1 + BANDt)) {1} else {0}"],
  ["z3", "z3a * z3b"],
  ["z4", "if (ER > (1 + BANDt)) {1} else {0}"],
  ["z5", "if (ER < (1 - BANDb)) {1} else {0}"],
  ["W", "W[-1] + omega3 * (omegat * P[-1] - W[-1])"],
  ["PR", "PR[-1] * (1 + GRpr)"],
  ["Nt", "Yk / PR"],
  ["N", "N[-1] + etan * (Nt - N[-1])"],
  ["WB", "N * W"],
  ["UC", "WB / Yk"],
  ["NUC", "W / PR"],
  ["NHUC", "(1 - sigman) * NUC + sigman * (1 + Rln[-1]) * NUC[-1]"],
  ["P", "(1 + phi) * NHUC"],
  ["phi", "phi[-1] + eps2 * (phit[-1] - phi[-1])"],
  ["phit", "(FUft + FDf + Rl[-1] * (Lfd[-1] - IN[-1])) / ((1 - sigmase) * Ske * UC + (1 + Rl[-1]) * sigmase * Ske * UC[-1])"],
  ["HCe", "(1 - sigmase) * Ske * UC + (1 + Rl[-1]) * sigmase * Ske * UC[-1]"],
  ["sigmase", "INk[-1] / Ske"],
  ["Fft", "FUft + FDf + Rl[-1] * (Lfd[-1] - IN[-1])"],
  ["FUft", "psiu * INV[-1]"],
  ["FDf", "psid * Ff[-1]"],
  ["Ff", "S - WB + (IN - IN[-1]) - Rl[-1] * IN[-1]"],
  ["FUf", "Ff - FDf - Rl[-1] * (Lfd[-1] - IN[-1]) + Rl[-1] * NPL"],
  ["Lfd", "Lfd[-1] + INV + (IN - IN[-1]) - FUf - (Eks - Eks[-1]) * Pe - NPL"],
  ["NPL", "NPLk * Lfs[-1]"],
  ["Eks", "Eks[-1] + ((1 - psiu) * INV[-1]) / Pe"],
  ["Rk", "FDf / (Pe[-1] * Ekd[-1])"],
  ["PE", "Pe / (Ff / Eks[-1])"],
  ["Q", "(Eks * Pe + Lfd) / (K + IN)"],
  ["YP", "WB + FDf + FDb + Rm[-1] * Mh[-1] + Rb[-1] * Bhd[-1] + BLs[-1]"],
  ["TX", "theta * YP"],
  ["YDr", "YP - TX - Rl[-1] * Lhd[-1]"],
  ["YDhs", "YDr + CG"],
  ["CG", "(Pbl - Pbl[-1]) * BLd[-1] + (Pe - Pe[-1]) * Ekd[-1] + (OFb - OFb[-1])"],
  ["V", "V[-1] + YDr - CONS + (Pbl - Pbl[-1]) * BLd[-1] + (Pe - Pe[-1]) * Ekd[-1] + (OFb - OFb[-1])"],
  ["Vk", "V / P"],
  ["CONS", "Ck * P"],
  ["Ck", "alpha1 * (YDkre + NLk) + alpha2 * Vk[-1]"],
  ["YDkre", "eps * YDkr + (1 - eps) * (YDkr[-1] * (1 + GRpr))"],
  ["YDkr", "YDr / P - ((P - P[-1]) * Vk[-1]) / P"],
  ["GL", "eta * YDr"],
  ["eta", "eta0 - etar * RRl"],
  ["NL", "GL - REP"],
  ["REP", "deltarep * Lhd[-1]"],
  ["Lhd", "Lhd[-1] + GL - REP"],
  ["NLk", "NL / P"],
  ["BUR", "(REP + Rl[-1] * Lhd[-1]) / YDr[-1]"],
  ["Bhd", "Vfma[-1] * (lambda20 + lambda22 * Rb[-1] - lambda21 * Rm[-1] - lambda24 * Rk[-1] - lambda23 * Rbl[-1] - lambda25 * (YDr / V))"],
  ["BLd", "Vfma[-1] * (lambda30 - lambda32 * Rb[-1] - lambda31 * Rm[-1] - lambda34 * Rk[-1] + lambda33 * Rbl[-1] - lambda35 * (YDr / V)) / Pbl"],
  ["Pe", "Vfma[-1] * (lambda40 - lambda42 * Rb[-1] - lambda41 * Rm[-1] + lambda44 * Rk[-1] - lambda43 * Rbl[-1] - lambda45 * (YDr / V)) / Ekd"],
  ["Mh", "Vfma - Bhd - Pe * Ekd - Pbl * BLd + Lhd"],
  ["Vfma", "V - Hhd - OFb"],
  ["VfmaA", "Mh + Bhd + Pbl * BLd + Pe * Ekd"],
  ["Hhd", "lambdac * CONS"],
  ["Ekd", "Eks"],
  ["G", "Gk * P"],
  ["Gk", "Gk[-1] * (1 + GRg)"],
  ["PSBR", "G + BLs[-1] + Rb[-1] * (Bbs[-1] + Bhs[-1]) - TX"],
  ["Bs", "Bs[-1] + G - TX - (BLs - BLs[-1]) * Pbl + Rb[-1] * (Bhs[-1] + Bbs[-1]) + BLs[-1]"],
  ["GD", "Bbs + Bhs + BLs * Pbl + Hs"],
  ["Fcb", "Rb[-1] * Bcbd[-1]"],
  ["BLs", "BLd"],
  ["Bhs", "Bhd"],
  ["Hhs", "Hhd"],
  ["Hbs", "Hbd"],
  ["Hs", "Hbs + Hhs"],
  ["Bcbd", "Hs"],
  ["Bcbs", "Bcbd"],
  ["Rb", "Rbbar"],
  ["Rbl", "Rb + ADDbl"],
  ["Pbl", "1 / Rbl"],
  ["Ms", "Mh"],
  ["Lfs", "Lfd"],
  ["Lhs", "Lhd"],
  ["Hbd", "ro * Ms"],
  ["Bbs", "Bbs[-1] + (Bs - Bs[-1]) - (Bhs - Bhs[-1]) - (Bcbs - Bcbs[-1])"],
  ["Bbd", "Ms + OFb - Lfs - Lhs - Hbd"],
  ["BLR", "Bbd / Ms"],
  ["Rm", "Rm[-1] + z1a * xim1 + z1b * xim2 - z2a * xim1 - z2b * xim2"],
  ["z2a", "if (BLR[-1] > (top + 0.05)) {1} else {0}"],
  ["z2b", "if (BLR[-1] > top) {1} else {0}"],
  ["z1a", "if (BLR[-1] <= bot) {1} else {0}"],
  ["z1b", "if (BLR[-1] <= (bot - 0.05)) {1} else {0}"],
  ["Rl", "Rm + ADDl"],
  ["OFbt", "NCAR * (Lfs[-1] + Lhs[-1])"],
  ["OFbe", "OFb[-1] + betab * (OFbt - OFb[-1])"],
  ["FUbt", "OFbe - OFb[-1] + NPLke * Lfs[-1]"],
  ["NPLke", "epsb * NPLke[-1] + (1 - epsb) * NPLk[-1]"],
  ["FDb", "Fb - FUb"],
  ["Fbt", "lambdab * Y[-1] + (OFbe - OFb[-1] + NPLke * Lfs[-1])"],
  ["Fb", "Rl[-1] * (Lfs[-1] + Lhs[-1] - NPL) + Rb[-1] * Bbd[-1] - Rm[-1] * Ms[-1]"],
  ["ADDl", "(Fbt - Rb[-1] * Bbd[-1] + Rm[-1] * (Ms[-1] - (1 - NPLke) * Lfs[-1] - Lhs[-1])) / ((1 - NPLke) * Lfs[-1] + Lhs[-1])"],
  ["FUb", "Fb - lambdab * Y[-1]"],
  ["OFb", "OFb[-1] + FUb - NPL"],
  ["CAR", "OFb / (Lfs + Lhs)"],
  ["Vf", "IN + K - Lfd - Ekd * Pe"],
  ["Ls", "Lfs + Lhs"]
] as const;

const growthExternalValues = {
  alpha1: 0.75,
  alpha2: 0.064,
  beta: 0.5,
  betab: 0.4,
  gamma: 0.15,
  gamma0: 0.00122,
  gammar: 0.1,
  gammau: 0.05,
  delta: 0.10667,
  deltarep: 0.1,
  eps: 0.5,
  eps2: 0.8,
  epsb: 0.25,
  epsrb: 0.9,
  eta0: 0.07416,
  etan: 0.6,
  etar: 0.4,
  theta: 0.22844,
  lambda20: 0.25,
  lambda21: 2.2,
  lambda22: 6.6,
  lambda23: 2.2,
  lambda24: 2.2,
  lambda25: 0.1,
  lambda30: -0.04341,
  lambda31: 2.2,
  lambda32: 2.2,
  lambda33: 6.6,
  lambda34: 2.2,
  lambda35: 0.1,
  lambda40: 0.67132,
  lambda41: 2.2,
  lambda42: 2.2,
  lambda43: 2.2,
  lambda44: 6.6,
  lambda45: 0.1,
  lambdab: 0.0153,
  lambdac: 0.05,
  xim1: 0.0008,
  xim2: 0.0007,
  ro: 0.05,
  sigman: 0.1666,
  sigmat: 0.2,
  psid: 0.15255,
  psiu: 0.92,
  omega0: -0.20594,
  omega1: 1,
  omega2: 2,
  omega3: 0.45621,
  ADDbl: 0.02,
  BANDt: 0.01,
  BANDb: 0.01,
  bot: 0.05,
  GRg: 0.03,
  GRpr: 0.03,
  Nfe: 87.181,
  NCAR: 0.1,
  NPLk: 0.02,
  Rbbar: 0.035,
  Rln: 0.07,
  RA: 0,
  top: 0.12
} as const;

const growthInitialValues = {
  sigmase: 0.16667,
  eta: 0.04918,
  phi: 0.26417,
  phit: 0.26417,
  ADDbl: 0.02,
  BANDt: 0.01,
  BANDb: 0.01,
  bot: 0.05,
  GRg: 0.03,
  GRpr: 0.03,
  Nfe: 87.181,
  NCAR: 0.1,
  NPLk: 0.02,
  Rbbar: 0.035,
  Rln: 0.07,
  RA: 0,
  top: 0.12,
  ADDl: 0.04592,
  BLR: 0.1091,
  BUR: 0.06324,
  Ck: 7334240,
  CAR: 0.09245,
  CONS: 52603100,
  ER: 1,
  Fb: 1744130,
  Fbt: 1744140,
  Ff: 18081100,
  Fft: 18013600,
  FDb: 1325090,
  FDf: 2670970,
  FUb: 419039,
  FUf: 15153800,
  FUft: 15066200,
  G: 16755600,
  Gk: 2336160,
  GL: 2775900,
  GRk: 0.03001,
  INV: 16911600,
  Ik: 2357910,
  N: 87.181,
  Nt: 87.181,
  NHUC: 5.6735,
  NL: 683593,
  NLk: 95311,
  NPL: 309158,
  NPLke: 0.02,
  NUC: 5.6106,
  omegat: 112852,
  P: 7.1723,
  Pbl: 18.182,
  Pe: 17937,
  PE: 5.07185,
  PI: 0.0026,
  PR: 138659,
  PSBR: 1894780,
  Q: 0.77443,
  Rb: 0.035,
  Rbl: 0.055,
  Rk: 0.03008,
  Rl: 0.06522,
  Rm: 0.0193,
  REP: 2092310,
  RRl: 0.06246,
  S: 86270300,
  Sk: 12028300,
  Ske: 12028300,
  TX: 17024100,
  U: 0.70073,
  UC: 5.6106,
  W: 777968,
  WB: 67824000,
  Y: 86607700,
  Yk: 12088400,
  YDr: 56446400,
  YDkr: 7813270,
  YDkre: 7813290,
  YP: 73158700,
  z1a: 0,
  z1b: 0,
  z2a: 0,
  z2b: 0,
  Bbd: 4389790,
  Bbs: 4389790,
  Bcbd: 4655690,
  Bcbs: 4655690,
  Bhd: 33439320,
  Bhs: 33439320,
  Bs: 42484800,
  BLd: 840742,
  BLs: 840742,
  GD: 57728700,
  Ekd: 5112.6001,
  Eks: 5112.6001,
  Hbd: 2025540,
  Hbs: 2025540,
  Hhd: 2630150,
  Hhs: 2630150,
  Hs: 4655690,
  IN: 11585400,
  INk: 2064890,
  INke: 2405660,
  INkt: 2064890,
  K: 127486471,
  Kk: 17774838,
  Lfd: 15962900,
  Lfs: 15962900,
  Lhd: 21606600,
  Lhs: 21606600,
  Ls: 37569500,
  Mh: 40510800,
  Ms: 40510800,
  OFb: 3474030,
  OFbe: 3474030,
  OFbt: 3638100,
  V: 165438779,
  Vfma: 159334599,
  Vk: 23066350,
  Vf: 31361792
} as const;

const growthEquationDescriptions: Record<string, string> = {
  ADDl: "Spread between interest rate on loans and rate on deposits",
  Bbd: "Government bills demanded by commercial banks",
  Bbs: "Government bills supplied to commercial banks",
  Bcbd: "Government bills demanded by Central bank",
  Bcbs: "Government bills supplied by Central bank",
  Bhd: "Demand for government bills from households",
  Bhs: "Government bills supplied to households",
  Bs: "Supply of government bills",
  BLd: "Demand for government bonds",
  BLs: "Supply of government bonds",
  BLR: "Gross bank liquidity ratio",
  BUR: "Burden of personal debt",
  Ck: "Real consumption",
  CAR: "Capital adequacy ratio of banks",
  CG: "Capital gains on government bonds",
  CONS: "Consumption at current prices",
  Ekd: "Number of equities demanded",
  Eks: "Number of equities supplied by firms",
  ER: "Employment rate",
  Fb: "Realized banks profits",
  Fbt: "Target profits of banks",
  Fcb: "Central bank \"profits\"",
  Ff: "Realized entrepreneurial profits",
  Fft: "Planned entrepreneurial profits",
  FDb: "Dividends of banks",
  FDf: "Dividends of firms",
  FUb: "Retained earnings of banks",
  FUbt: "Targt retained earnings of banks",
  FUf: "Retained earnings of firms",
  FUft: "Planned retained earnings of firms",
  G: "Government expenditures",
  Gk: "Real government expenditures",
  GD: "Government debt",
  GL: "Gross amount of new personal loans",
  GRk: "growth_mod of real capital stock",
  Hbd: "Cash required by banks",
  Hbs: "Cash supplied to banks",
  Hhd: "Households demand for cash",
  Hhs: "Cash supplied to households",
  Hs: "Total supply of cash",
  HCe: "Expected historical costs",
  INV: "Gross investment",
  Ik: "Gross investment in real terms",
  IN: "Stock of inventories at current costs",
  INk: "Real inventories",
  INke: "Expected real inventories",
  INkt: "Target level of real inventories",
  K: "Capital stock",
  Kk: "Real capital stock",
  Lfd: "Demand for loans by firms",
  Lfs: "Supply of loans to firms",
  Lhd: "Demand for loans by households",
  Lhs: "Loans supplied to households",
  Mh: "Deposits demanded by households",
  Ms: "Deposits supplied by banks",
  N: "Employment level",
  Nt: "Desired employment level",
  NHUC: "Normal historic unit cost",
  NL: "Net flow of new loans to the household sector",
  NLk: "Real flow of new loans to the household sector",
  NPL: "Non-Performing loans",
  NPLke: "Expected proportion of Non-Performing Loans",
  NUC: "Normal unit cost",
  OFb: "Own funds of banks",
  OFbe: "Short-run target for banks own funds",
  OFbt: "Long-run target for banks own funds",
  omegat: "Target real wage for workers",
  P: "Price level",
  Pbl: "Price of government bonds",
  Pe: "Price of equities",
  PE: "Price earnings ratio",
  PI: "Price inflation",
  PR: "Lobor productivity",
  PSBR: "Government deficit",
  Q: "Tobin's Q",
  Rb: "Interest rate on government bills",
  Rbl: "Interest rate on bonds",
  Rk: "Dividend yield of firms",
  Rl: "Interest rate on loans",
  Rm: "Interest rate on deposits",
  REP: "Personal loans repayments",
  RRl: "Real interest rate on loans",
  S: "Sales at current prices",
  Sk: "Real sales",
  Ske: "Expected real sales",
  U: "Capital utilization proxy",
  UC: "Unit costs",
  V: "Wealth of households",
  Vk: "Real wealth of households",
  Vfma: "Investible wealth of households",
  W: "Wage rate",
  WB: "The wage bill",
  Y: "Output at current prices (nominal GDP ",
  Yk: "Real output",
  YDhs: "Haig-Simons measure of disposable income",
  YDr: "Regular disposable income",
  YDkr: "Regular real disposable income",
  YDkre: "Expected regular real disposable income",
  YP: "Personal income",
  eta: "Ratio of new loans to personal income",
  phi: "Mark-up on unit costs",
  phit: "Ideal mark-up on unit costs",
  z1a: "Is one if bank liquidity ratio is below bottom range",
  z1b: "Is one if bank liquidity ratio is below bottom range",
  z2a: "Is one if bank liquidity ratio is above top range",
  z2b: "Is one if bank liquidity ratio is above top range",
  z3: "Parameter in wage aspiration equation",
  z4: "Parameter in wage aspiration equation",
  z5: "Parameter in wage aspiration equation",
  sigmase: "Opening inventories to expected sales ratio",
  TX: "Taxes"
};

const growthExternalDescriptions: Record<string, string> = {
  alpha1: "Propensity to consume out of income",
  alpha2: "Propensity to consume out of wealth",
  beta: "Parameter in expectation formations on real sales",
  betab: "Spped of adjustment of banks own funds",
  bot: "Bottom value for bank net liquidity ratio",
  delta: "Rate of depreciation of fixed capital",
  deltarep: "Ratio of personal loans repayments to stock of loans",
  eps: "Parameter in expectation formations on real disposable income",
  eps2: "Speed of adjustment of mark-up",
  epsb: "Speed of adjustment in expected proportion of non-performing loans",
  epsrb: "Speed of adjustment in the real interest rate on bills",
  eta0: "Ratio of new loans to personal income - exogenous component",
  etan: "Speed of adjustment of actual employment to desired employment",
  etar: "Relation between the ratio of new loans to personal income and the interest rate on loans",
  gamma: "Speed of adjustment of inventories to the target level",
  gamma0: "Exogenous growth_mod in the real stock of capital",
  gammar: "Relation between the real interest rate and growth_mod in the stock of capital",
  gammau: "Relation between the utilization rate and growth_mod in the stock of capital",
  lambda20: "Parameter in households demand for bills",
  lambda21: "Parameter in households demand for bills",
  lambda22: "Parameter in households demand for bills",
  lambda23: "Parameter in households demand for bills",
  lambda24: "Parameter in households demand for bills",
  lambda25: "Parameter in households demand for bills",
  lambda30: "Parameter in households demand for bonds",
  lambda31: "Parameter in households demand for bonds",
  lambda32: "Parameter in households demand for bonds",
  lambda33: "Parameter in households demand for bonds",
  lambda34: "Parameter in households demand for bonds",
  lambda35: "Parameter in households demand for bonds",
  lambda40: "Parameter in households demand for equities",
  lambda41: "Parameter in households demand for equities",
  lambda42: "Parameter in households demand for equities",
  lambda43: "Parameter in households demand for equities",
  lambda44: "Parameter in households demand for equities",
  lambda45: "Parameter in households demand for equities",
  lambdab: "Parameter determining dividends of banks",
  lambdac: "Parameter in households demand for cash",
  psid: "Ratio of dividends to gross profits",
  psiu: "Ratio of retained earnings to investments",
  ro: "Reserve requirement parameter",
  sigman: "Parameter of influencing normal historic unit costs",
  theta: "Income tax rate",
  top: "Top value for bank net liquidity ratio",
  xim1: "Parameter in the equation for setting interest rate on deposits",
  xim2: "Parameter in the equation for setting interest rate on deposits",
  omega0: "Parameter influencing the target real wage for workers",
  omega1: "Parameter influencing the target real wage for workers",
  omega2: "Parameter influencing the target real wage for workers",
  omega3: "Speed of adjustment of wages to target value",
  ADDbl: "Spread between long-term interest rate and rate on bills",
  BANDb: "Lower range of the flat Phillips curve",
  BANDt: "Upper range of the flat Phillips curve",
  GRg: "growth_mod of real government expenditures",
  GRpr: "growth_mod rate of productivity",
  NCAR: "Normal capital adequacy ratio of banks",
  Nfe: "Full employment level",
  NPLk: "Proportion of Non-Performing loans",
  RA: "Random shock to expectations on real sales",
  Rbbar: "Interest rate on bills, set exogenously",
  Rln: "Normal interest rate on loans",
  sigmat: "Target inventories to sales ratio"
};

const growthModel: ModelDefinition = {
  equations: growthEquationTuples.map(([name, expression]) => ({ name, expression })),
  externals: Object.fromEntries(
    Object.entries(growthExternalValues).map(([name, value]) => [name, { kind: "constant", value }])
  ),
  initialValues: growthInitialValues
};

const growthOptions: SimulationOptions = {
  periods: 350,
  solverMethod: "GAUSS_SEIDEL",
  tolerance: 1e-15,
  maxIterations: 350,
  defaultInitialValue: 1e-15,
  hiddenEquation: {
    leftVariable: "Bbs",
    rightVariable: "Bbd",
    tolerance: 1e-6,
    relative: true
  }
};

const growthEditor = editorStateFromModel(growthModel, growthOptions);
growthEditor.equations = growthEditor.equations.map((equation) => ({
  ...equation,
  desc: growthEquationDescriptions[equation.name] ?? equation.desc
}));
growthEditor.externals = growthEditor.externals.map((external) => ({
  ...external,
  desc: growthExternalDescriptions[external.name] ?? external.desc
}));

export const gl8GrowthNotebook: NotebookDocument = {
  id: "gl8-growth-notebook",
  title: "GL8 Growth Notebook",
  metadata: {
    version: 1,
    template: "gl8-growth"
  },
  cells: [
    {
      id: "intro",
      type: "markdown",
      title: "Overview",
      source:
        "This notebook adapts the `gl8-growth.Rmd` article into executable browser cells. It includes the full GROWTH baseline, the balance-sheet and transactions-flow matrices, and three representative policy experiments from the article: a higher target real wage, a one-period fiscal-growth shock, and a rise in non-performing loans."
    },
    {
      id: "balance-sheet",
      type: "matrix",
      title: "GROWTH balance sheet",
      sourceRunCellId: "baseline-run",
      columns: ["Households", "Firms", "Govt", "Central Bank", "Banks", "Sum"],
      rows: [
        { label: "Inventories", values: ["", "+IN", "", "", "", "+IN"] },
        { label: "Fixed capital", values: ["", "+K", "", "", "", "+K"] },
        { label: "HPM", values: ["+Hhd", "", "", "-Hs", "+Hbd", "0"] },
        { label: "Money", values: ["+Mh", "", "", "", "-Ms", "0"] },
        { label: "Bills", values: ["+Bhd", "", "-Bs", "+Bcbd", "+Bbd", "0"] },
        { label: "Bonds", values: ["+BLd * Pbl", "", "-BLs * Pbl", "", "", "0"] },
        { label: "Loans", values: ["-Lhd", "-Lfd", "", "", "+Ls", "0"] },
        { label: "Equities", values: ["+Ekd * Pe", "-Eks * Pe", "", "", "", "0"] },
        { label: "Bank capital", values: ["+OFb", "", "", "", "-OFb", "0"] },
        { label: "Balance", values: ["-V", "-Vf", "GD", "", "", "-(IN + K)"] }
      ],
      description: "Balance-sheet matrix for model GROWTH following the gl8 article.",
      note: "Validated against the baseline simulation in the R vignette fixture."
    },
    {
      id: "transaction-flow",
      type: "matrix",
      title: "GROWTH transactions-flow matrix",
      sourceRunCellId: "baseline-run",
      columns: [
        "Households",
        "Firms curr.",
        "Firms cap.",
        "Govt.",
        "CB curr.",
        "CB cap.",
        "Banks curr.",
        "Banks cap."
      ],
      rows: [
        { label: "Consumption", values: ["-CONS", "+CONS", "", "", "", "", "", ""] },
        { label: "Govt. exp.", values: ["", "+G", "", "-G", "", "", "", ""] },
        { label: "Investment", values: ["", "+INV", "-INV", "", "", "", "", ""] },
        { label: "Inventories", values: ["", "+(IN - IN[-1])", "-(IN - IN[-1])", "", "", "", "", ""] },
        { label: "Taxes", values: ["-TX", "", "", "+TX", "", "", "", ""] },
        { label: "Wages", values: ["+WB", "-WB", "", "", "", "", "", ""] },
        { label: "Inventory financing cost", values: ["", "-Rl[-1] * IN[-1]", "", "", "", "", "+Rl[-1] * IN[-1]", ""] },
        { label: "Entrepreneurial profits", values: ["+FDf", "-Ff", "+FUf", "", "", "", "+Rl[-1] * (Lfs[-1] - IN[-1] - NPL)", ""] },
        { label: "Banks profits", values: ["+FDb", "", "", "", "", "", "-Fb", "+FUb"] },
        { label: "Int. hh loans", values: ["-Rl[-1] * Lhd[-1]", "", "", "", "", "", "+Rl[-1] * Lhs[-1]", ""] },
        { label: "Int. deposits", values: ["+Rm[-1] * Mh[-1]", "", "", "", "", "", "-Rm[-1] * Ms[-1]", ""] },
        { label: "Int. bills", values: ["+Rb[-1] * Bhd[-1]", "", "", "-Rb[-1] * Bs[-1]", "+Rb[-1] * Bcbd[-1]", "", "+Rb[-1] * Bbd[-1]", ""] },
        { label: "Int. bonds", values: ["+BLd[-1]", "", "", "-BLd[-1]", "", "", "", ""] },
        { label: "Ch. loans", values: ["+(Lhd - Lhd[-1])", "", "+(Lfd - Lfd[-1])", "", "", "", "", "-(Ls - Ls[-1])"] },
        { label: "Ch. cash", values: ["-(Hhd - Hhd[-1])", "", "", "", "", "+(Hs - Hs[-1])", "", "-(Hbd - Hbd[-1])"] },
        { label: "Ch. deposits", values: ["-(Mh - Mh[-1])", "", "", "", "", "", "", "+(Ms - Ms[-1])"] },
        { label: "Ch. bills", values: ["-(Bhd - Bhd[-1])", "", "", "+(Bs - Bs[-1])", "", "-(Bcbd - Bcbd[-1])", "", "-(Bbd - Bbd[-1])"] },
        { label: "Ch. bonds", values: ["-(BLd - BLd[-1]) * Pbl", "", "", "+(BLs - BLs[-1]) * Pbl", "", "", "", ""] },
        { label: "Ch. equities", values: ["-(Ekd - Ekd[-1]) * Pe", "", "+(Eks - Eks[-1]) * Pe", "", "", "", "", ""] },
        { label: "Loan defaults", values: ["", "", "+NPL", "", "", "", "", "-NPL"] }
      ],
      description: "Transactions-flow matrix for model GROWTH following the gl8 article.",
      note: "Validated against the baseline simulation in the R vignette fixture."
    },
    {
      id: "transaction-flow-sequence",
      type: "sequence",
      title: "GROWTH transaction flow sequence",
      source: { kind: "matrix", matrixCellId: "transaction-flow" },
      description: "Sequence view generated from the GROWTH transactions-flow matrix at the selected simulation period."
    },
    {
      id: "equation-dependency-graph",
      type: "sequence",
      title: "GROWTH equation dependency graph",
      source: { kind: "dependency", modelId: "equations" },
      description:
        "Layered dependency view of the GROWTH equations. Left-to-right position shows dependency depth and top-to-bottom order follows the notebook equation list within each layer.",
      note:
        "This view is intentionally dense. Use it to inspect how the large GROWTH model clusters into exogenous inputs, intermediate flows, and downstream stocks."
    },
    {
      id: "equations",
      type: "model",
      title: "GROWTH model",
      editor: growthEditor
    },
    {
      id: "baseline-run",
      type: "run",
      title: "Baseline run",
      sourceModelCellId: "equations",
      mode: "baseline",
      resultKey: "gl8_growth_baseline",
      description: "Baseline GROWTH simulation with the relative hidden-equation condition Bbs = Bbd."
    },
    {
      id: "baseline-chart",
      type: "chart",
      title: "Baseline steady-state checks",
      sourceRunCellId: "baseline-run",
      variables: ["Yk", "PI", "GRk", "BLR", "CAR"],
      axisMode: "separate",
      axisSnapTolarance: 0.5,
      seriesRanges: {
        PI: { includeZero: true },
        GRk: { includeZero: true },
        BLR: { includeZero: true },
        CAR: { includeZero: true }
      }
    },
    {
      id: "baseline-table",
      type: "table",
      title: "Baseline variable summary",
      sourceRunCellId: "baseline-run",
      variables: ["Yk", "Ck", "Ik", "P", "Rl", "BLR", "CAR", "GD"]
    },
    {
      id: "scenario-1-note",
      type: "markdown",
      title: "Scenario 1",
      source:
        "Scenario 1 follows the article's first experiment: `omega0` rises from `-0.20594` to `-0.1` from periods 5 to 150, raising the target real wage."
    },
    {
      id: "scenario-1-run",
      type: "run",
      title: "Scenario 1: higher target real wage",
      sourceModelCellId: "equations",
      mode: "scenario",
      scenario: {
        shocks: [
          {
            startPeriodInclusive: 5,
            endPeriodInclusive: 150,
            variables: {
              omega0: { kind: "constant", value: -0.1 }
            }
          }
        ]
      },
      resultKey: "gl8_growth_s1"
    },
    {
      id: "scenario-1-chart",
      type: "chart",
      title: "Scenario 1 inflation, wage, and output",
      sourceRunCellId: "scenario-1-run",
      variables: ["PI", "W", "Yk", "Ck"],
      axisMode: "separate",
      axisSnapTolarance: 0.5,
      seriesRanges: {
        PI: { includeZero: true }
      }
    },
    {
      id: "scenario-2-note",
      type: "markdown",
      title: "Scenario 2",
      source:
        "Scenario 2 applies the one-period fiscal-growth shock from the article: `GRg` rises from `0.03` to `0.035` for periods 10 to 11."
    },
    {
      id: "scenario-2-run",
      type: "run",
      title: "Scenario 2: one-period fiscal growth shock",
      sourceModelCellId: "equations",
      mode: "scenario",
      scenario: {
        shocks: [
          {
            startPeriodInclusive: 10,
            endPeriodInclusive: 11,
            variables: {
              GRg: { kind: "constant", value: 0.035 }
            }
          }
        ]
      },
      resultKey: "gl8_growth_s2"
    },
    {
      id: "scenario-2-chart",
      type: "chart",
      title: "Scenario 2 output, deficit, and debt",
      sourceRunCellId: "scenario-2-run",
      variables: ["Gk", "Yk", "PSBR", "GD"],
      axisMode: "separate",
      axisSnapTolarance: 0.5
    },
    {
      id: "scenario-10-note",
      type: "markdown",
      title: "Scenario 10",
      source:
        "Scenario 10 raises non-performing loans as in the article: `NPLk` rises from `0.02` to `0.05` from periods 10 to 150."
    },
    {
      id: "scenario-10-run",
      type: "run",
      title: "Scenario 10: higher non-performing loans",
      sourceModelCellId: "equations",
      mode: "scenario",
      scenario: {
        shocks: [
          {
            startPeriodInclusive: 10,
            endPeriodInclusive: 150,
            variables: {
              NPLk: { kind: "constant", value: 0.05 }
            }
          }
        ]
      },
      resultKey: "gl8_growth_s10"
    },
    {
      id: "scenario-10-chart",
      type: "chart",
      title: "Scenario 10 bank stress indicators",
      sourceRunCellId: "scenario-10-run",
      variables: ["NPL", "CAR", "Rl", "OFb"],
      axisMode: "separate",
      axisSnapTolarance: 0.5,
      seriesRanges: {
        CAR: { includeZero: true },
        Rl: { includeZero: true }
      }
    }
  ]
};
